# Data Analysis Test

Use file `./ref/crop_data.csv` for input

Use `pandas` lib

Write your code and display readable result

In [1]:
import pandas as pd

In [2]:
# read csv file

df = pd.read_csv("./ref/crop_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   crop_year         11914 non-null  object 
 1   year              11914 non-null  int64  
 2   product           11914 non-null  object 
 3   province          11914 non-null  object 
 4   area_plant_rai    11769 non-null  float64
 5   area_harvest_rai  11728 non-null  float64
 6   production_ton    11692 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 651.7+ KB


### Example Question

How many "ยางพารา" produced in whole country ("ทั้งประเทศ")


In [ ]:
# How many "ยางพารา" produced in whole country ("ทั้งประเทศ")
new_df = df.loc[
    (df["product"] == "ยางพารา" ) &
    (df["province"] == "ทั้งประเทศ") 
]
sum(new_df["production_ton"])


crop_year  year  product    province  area_plant_rai  area_harvest_rai  \
4035      2550  2550  ยางพารา  ทั้งประเทศ    1.805473e+07      1.294911e+07   
4036      2551  2551  ยางพารา  ทั้งประเทศ    1.880883e+07      1.335202e+07   
4037      2552  2552  ยางพารา  ทั้งประเทศ    1.962545e+07      1.374067e+07   
4038      2553  2553  ยางพารา  ทั้งประเทศ    2.026442e+07      1.488278e+07   
4039      2554  2554  ยางพารา  ทั้งประเทศ    2.116507e+07      1.576040e+07   
4040      2555  2555  ยางพารา  ทั้งประเทศ    2.248182e+07      1.671039e+07   
4041      2556  2556  ยางพารา  ทั้งประเทศ    2.319417e+07      1.738584e+07   
4042      2557  2557  ยางพารา  ทั้งประเทศ    2.358321e+07      1.815882e+07   
4043      2558  2558  ยางพารา  ทั้งประเทศ    2.314037e+07      1.842593e+07   
4044      2559  2559  ยางพารา  ทั้งประเทศ    2.293310e+07      1.846649e+07   
4045      2560  2560  ยางพารา  ทั้งประเทศ    2.285218e+07      1.910674e+07   
4826      2561  2561  ยางพารา  ทั้งประเทศ    2.262628e+07      2.002310e+07   

      production_ton  
4035       3055251.0  
4036       3212702.0  
4037       3329368.0  
4038       3585600.0  
4039       3924865.0  
4040       3897093.0  
4041       4192962.0  
4042       4415687.0  
4043       4413748.0  
4044       4342935.0  
4045       4503101.0  
4826       4813527.0

### Question 1

How many "ข้าวนาปี" produced in "ยะลา" between year 2550 - 2553


In [37]:
# Write you code and display question 1 result here.
Q1_df = df.loc[
    (df["product"] == "ข้าวนาปี" ) &
    (df["province"] == "ยะลา") &
    (df['year'] >= 2550) & 
    (df['year'] <= 2553)
]
# display(Q1_df)
sum(Q1_df["production_ton"])


87707.0

### Question 2

Calculate harvest rate of "ข้าวนาปี" in whole country

_harvest rate = area_harvest_rai / area_plant_rai_

In [38]:
df.head()

crop_year  year   product    province  area_plant_rai  area_harvest_rai  \
0   2549/50  2550  ข้าวนาปี  ทั้งประเทศ      57541825.0        53500163.0   
1   2550/51  2551  ข้าวนาปี  ทั้งประเทศ      57385921.0        53892143.0   
2   2551/52  2552  ข้าวนาปี  ทั้งประเทศ      57422337.0        54385144.0   
3   2552/53  2553  ข้าวนาปี  ทั้งประเทศ      57497441.0        54739638.0   
4   2553/54  2554  ข้าวนาปี  ทั้งประเทศ      64574071.0        59690203.0   

   production_ton  
0      23108401.0  
1      23582596.0  
2      23508833.0  
3      23430770.0  
4      25742917.0

In [53]:
# Write you code and display question 2 result here.
# replace with your code
area_harvest_rai = 0   
area_plant_rai = 0
harvest_rate = 0

Q2_df = df.loc[
    (df["product"] == "ข้าวนาปี" ) &
    (df["province"] == "ทั้งประเทศ") 
]

Q2_df['harvest_rate'] = Q2_df['area_harvest_rai']/Q2_df['area_plant_rai'].replace(0, pd.NA)

area_harvest_rai = sum(Q2_df['area_harvest_rai'])
area_plant_rai = sum(Q2_df['area_plant_rai'])
harvest_rate = area_harvest_rai / area_plant_rai

print('area_harvest_rai', area_harvest_rai)
print('area_plant_rai', area_plant_rai)
print('harvest_rate', harvest_rate)

area_harvest_rai 730340255.0
area_plant_rai 783456906.0
harvest_rate 0.9322022046225986


C:\Users\ky_tr\AppData\Local\Temp\ipykernel_12884\504283599.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Q2_df['harvest_rate'] = Q2_df['area_harvest_rai']/Q2_df['area_plant_rai'].replace(0, pd.NA)


### Question 3

Calculate total profit of "ข้าวโพดฝักอ่อน" produced in "ภาคเหนือ" from year 2555 to 2562
- profit rate in year 2555 - year 2559 is 50% (selling price is 50THB/kg.)
- profit rate in year 2560 - year 2562 is 30% (selling price is 120THB/kg.)
- assume all product was sold out every year.


In [63]:
# Write you code and display question 3 result here.
Q3_df = df.loc[
    (df["product"] == "ข้าวโพดฝักอ่อน" ) &
    (df["province"] == "ภาคเหนือ") &
    (df["year"] >= 2555) &
    (df["year"] <= 2562)
]

profit_rate_2555_2559 = 0.50
profit_rate_2560_2562 = 0.30
selling_price_2555_2559 = 50  # THB/kg
selling_price_2560_2562 = 120  # THB/kg

cost_price_2555_2559 = selling_price_2555_2559 / (1 + profit_rate_2555_2559)
cost_price_2560_2562 = selling_price_2560_2562 / (1 + profit_rate_2560_2562)

profit_per_ton_2555_2559 = selling_price_2555_2559 - cost_price_2555_2559
profit_per_ton_2560_2562 = selling_price_2560_2562 - cost_price_2560_2562

Q3_df_2555_2559 = Q3_df[(Q3_df['year'] >= 2555) & (Q3_df['year'] <= 2559)]
Q3_df_2560_2562 = Q3_df[(Q3_df['year'] >= 2560) & (Q3_df['year'] <= 2562)]

total_profit_2555_2559 = (Q3_df_2555_2559['production_ton'] * profit_per_ton_2555_2559).sum()
total_profit_2560_2562 = (Q3_df_2560_2562['production_ton'] * profit_per_ton_2560_2562).sum()

total_cost_2555_2559 = (Q3_df_2555_2559['production_ton'] * cost_price_2555_2559).sum()
total_cost_2560_2562 = (Q3_df_2560_2562['production_ton'] * cost_price_2560_2562).sum()

total_profit = total_profit_2555_2559 + total_profit_2560_2562
total_cost = total_cost_2555_2559 + total_cost_2560_2562

overall_profit_rate = total_profit / total_cost * 100

print(f"Overall profit rate from 2555 to 2562: {overall_profit_rate:.2f}%")

Overall profit rate from 2555 to 2562: 37.78%


### Question 4

Form question 3, display the dataframe with 'year', 'production_ton', 'income', 'profit_thb' column


In [71]:
# Write you code and display question 4 result here.
Q3_df.loc[Q3_df['year'] <= 2559, 'income'] = Q3_df['production_ton']*1000 * selling_price_2555_2559
Q3_df.loc[Q3_df['year'] <= 2559, 'cost'] = Q3_df['production_ton']*1000 * cost_price_2555_2559
Q3_df.loc[Q3_df['year'] <= 2559, 'profit_thb'] = Q3_df['income'] - Q3_df['cost']

Q3_df.loc[Q3_df['year'] >= 2560, 'income'] = df['production_ton']*1000 * selling_price_2560_2562
Q3_df.loc[Q3_df['year'] >= 2560, 'cost'] = Q3_df['production_ton']*1000 * cost_price_2560_2562
Q3_df.loc[Q3_df['year'] >= 2560, 'profit_thb'] = Q3_df['income'] - Q3_df['cost']

Q4_df = Q3_df[['year','production_ton','income','profit_thb']]

display(Q4_df)

year  production_ton        income    profit_thb
11690  2555         24741.0  1.237050e+09  4.123500e+08
11691  2556         25371.0  1.268550e+09  4.228500e+08
11692  2557         21788.0  1.089400e+09  3.631333e+08
11693  2558         20499.0  1.024950e+09  3.416500e+08
11694  2559         19332.0  9.666000e+08  3.222000e+08
11695  2560         21329.0  2.559480e+09  5.906492e+08
11696  2561         21757.0  2.610840e+09  6.025015e+08
11697  2562         20349.0  2.441880e+09  5.635108e+08

### Question 5

We plan to invest in growing soybeans (ถั่วเหลือง) which province should we invest.

We looking for
- high protential area (high havest_rate)
- we want market share only 20% but production_ton should be more than 2000 in the past (2550 - 2562)



In [105]:

# Write you code and display question 5 result here.


Q5_df = df.loc[
    (df["product"] == "ถั่วเหลือง" ) &
    (~df["province"].isin(['ทั้งประเทศ', 'ภาคเหนือ', 'ภาคตะวันออกเฉียงเหนือ', 'ภาคกลาง'])) &  # Exclude specific provinces
    (df["production_ton"] > 2000) 
]

Q5_df_by_province = Q5_df.groupby('province').agg({
    'area_plant_rai': 'mean',
    'area_harvest_rai' : 'mean',
    'production_ton': 'sum'
}).reset_index()

Q5_df_by_province['harvest_rate'] = (Q5_df_by_province['area_harvest_rai']/Q5_df_by_province['area_plant_rai'].replace(0, pd.NA)).round(3)

Q5_df_by_province['market_share'] = Q5_df_by_province['production_ton']/sum(Q5_df_by_province['production_ton'])

display(Q5_df_by_province.sort_values(by='harvest_rate', ascending=False))

province  area_plant_rai  area_harvest_rai  production_ton  \
18   แม่ฮ่องสอน    53555.384615      53109.538462        216298.0   
17         แพร่    56144.444444      55583.222222        119702.0   
3    ฉะเชิงเทรา    10859.500000      10724.000000          6960.0   
13     เชียงราย    23555.615385      23215.461538         68852.0   
14    เชียงใหม่    66596.111111      65411.777778        174554.0   
15    เพชรบูรณ์     9983.000000       9794.000000          2443.0   
9       สระแก้ว    43328.000000      42509.500000         29491.0   
5           ตาก    36594.285714      35750.571429         61549.0   
6          น่าน    20088.666667      19597.666667         59940.0   
12    อุตรดิตถ์    37506.500000      36539.000000         52891.0   
1       ขอนแก่น    30163.846154      29234.923077         93938.0   
11  หนองบัวลำภู    20458.285714      19819.142857         29998.0   
2      จันทบุรี     6844.000000       6632.000000          2029.0   
8         ลำปาง    22868.222222      22119.777778         45751.0   
4       ชัยภูมิ    32616.250000      31506.916667         88553.0   
0     กำแพงเพชร    27544.250000      26398.000000         30483.0   
7      พิษณุโลก    28235.250000      26893.250000         29782.0   
10      สุโขทัย    26407.200000      25083.200000         71932.0   
16          เลย    43542.333333      41337.888889         98856.0   

    harvest_rate  market_share  
18         0.992      0.168456  
17         0.990      0.093226  
3          0.988      0.005421  
13         0.986      0.053623  
14         0.982      0.135945  
15         0.981      0.001903  
9          0.981      0.022968  
5          0.977      0.047935  
6          0.976      0.046682  
12         0.974      0.041192  
1          0.969      0.073160  
11         0.969      0.023363  
2          0.969      0.001580  
8          0.967      0.035632  
4          0.966      0.068966  
0          0.958      0.023741  
7          0.952      0.023195  
10         0.950      0.056022  
16         0.949      0.076991

In [106]:
sum(Q5_df_by_province['market_share'])

1.0